<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5x4rj1x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5x4rj1x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5x4rj1x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5x4rj1x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5x4rj1x\appDevDebugProjectContainer([
    'container.build_hash' => '5x4rj1x',
    'container.build_id' => 'df62741c',
    'container.build_time' => 1555522725,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5x4rj1x');
